language: C++
sudo: required
os:
  - linux
addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - python3.6
      - gcc-7
      - g++-7
compiler:
  - g++-7
before_script:
  - ./travis/build_env.sh
  - lsb_release -a
  - g++ --version
  - g++-7 --version
  - mpif90 -show
  - python3 --version
script:
  - ./travis/build_and_test.sh
