language: C++
sudo: required
os:
  - linux
compiler:
  - gcc
before_script:
  - ./travis/build_env.sh
  - lsb_release -a
  - g++ --version
  - mpif90 -show
  - python3 --version
script:
  - ./travis/build_and_test.sh
